name: fireflyluciferin
title: Firefly Luciferin
base: core24
version: 'VERSION_PLACEHOLDER'
summary: Ambient lighting software
description: |
  Ambient Lighting or Bias Light is a technology that enhances your viewing experience by projecting colored lights onto the wall behind
            your TV/Monitor, matching the colors on the screen. This creates a more immersive and engaging atmosphere, making your favorite shows,
            movies, and games feel even more captivating.
        Luciferin is a generic term for the light-emitting compound found in organisms that generate bioluminescence like Fireflies and Glow Worms.
            Firefly Luciferin is a Java Fast Screen Capture PC software designed for Glow Worm Luciferin firmware,
            those two software create the perfect Bias Lighting and Ambient Light system for PC.
            Differently from other solutions, Firefly and Glow Worm Luciferin are designed to work together for the best experience possible.
website: https://github.com/sblantipodi/firefly_luciferin
contact: https://github.com/sblantipodi/firefly_luciferin/issues
issues: https://github.com/sblantipodi/firefly_luciferin/issues
source-code: https://github.com/sblantipodi/firefly_luciferin
icon: fireflyluciferin.png
license: GPL-3.0

grade: stable
confinement: strict

apps:
  fireflyluciferin:
    command: bin/FireflyLuciferin
    desktop: usr/share/applications/fireflyluciferin.desktop
    extensions: [ gnome ]
    plugs:
      - network
      - home
      - pulseaudio
      - x11
      - desktop
      - desktop-legacy
      - audio-playback
      - audio-record
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      DISABLE_WAYLAND: 1
      NOTIFY_IGNORE_PORTAL: 1

parts:
  compiledpackage:
    source-type: deb
    plugin: dump
    source: FireflyLuciferinLinux.deb

  fireflyluciferin:
    plugin: nil
    source: .
    source-type: local
    build-packages:
      - wget
      - libgtk2.0-dev
      - libzstd1
      - zstd
      - tar
    stage-packages:
      - xdg-user-dirs
      - xdg-utils
      - libgtk-3-0
      - libxtst6
      - libglib2.0-dev
      - gstreamer1.0-tools
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-qt5
      - gstreamer1.0-x
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libayatana-appindicator3-1
      - libayatana-appindicator3-dev
      - libayatana-indicator3-7
      - libayatana-ido3-0.4-0
      - libnotify-dev
      - libnotify4
      - libnotify-bin
      - libatlas3-base
      - libblas3
      - libpulse0
      - pulseaudio-utils
      - libpulse-dev
      - libasound2
      - libasound2-plugins
      - alsa-utils

    override-build: |
      snapcraftctl build
      ls -la
      ar x FireflyLuciferinLinux.deb
      tar xvf data.tar.zst
      ls -la
      ls -la opt/fireflyluciferin
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui      
      cp -R opt/fireflyluciferin/* $SNAPCRAFT_PART_INSTALL
      cp opt/fireflyluciferin/lib/app/classes/build_assets/org.dpsoftware.FireflyLuciferin.snap.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/fireflyluciferin.desktop
      cp opt/fireflyluciferin/lib/app/classes/org/dpsoftware/gui/img/luciferin_logo.png $SNAPCRAFT_PART_INSTALL/meta/gui/fireflyluciferin.png
